// Auto-generated by generate-build-info.sh — do not edit manually.
// This file is tracked in git so the app always compiles, but the commit hash
// gets updated before each build to embed the current HEAD.
enum BuildInfo {
  static let builtCommit = "fef8761eca95f6180ed2c3e0300724a13a47761e"
}
